//! Making a weak model's tool calls survivable: repairing the arguments
//! blob it streamed, and checking it against the manifest before a tool
//! ever sees it.
//!
//! Both halves exist because of the same observation. A capable model emits
//! one well-formed JSON object per `tool_use` and the harness can pass it
//! through untouched. A small model — or a gateway translating for one —
//! emits it *nearly* right: two objects concatenated, a trailing fragment of
//! a chat template, a bare string where an object belongs, a missing
//! required field. None of that should be able to hurt the session, and all
//! of it should come back as something the model can act on.
//!
//! ## Why repair happens before journaling
//!
//! `Json(input)` in a `ToolUse` block is replayed onto the wire on every
//! subsequent request of the turn. If it is not parseable JSON, an endpoint
//! that parses it (litellm does) rejects *every* later request — the session
//! is bricked, and no retry or resume recovers it, because the poison is in
//! the log. That is the "never write a record kind that cannot be replayed"
//! invariant with a very sharp edge, so [`repair_tool_input`] runs in the
//! assembler and what gets journaled is always a JSON object.
//!
//! ## Why validation produces prose
//!
//! A schema violation that reaches a Rune script surfaces as an interpreter
//! error (`Field \`path\` not available on \`::std::tuple::Tuple\``), which
//! tells the model nothing it can use. [`validate`] instead answers in the
//! terms the model is working in: which tool, which field, what was expected,
//! what arrived, and a synthesised example call. Recovering from a bad call
//! is then one obvious step rather than a guess.
//!
//! The supported subset of JSON Schema is what tool manifests actually use:
//! `type`, `properties`, `required`, `enum`, `items` — and, since schemas
//! generated by schemars (Melete's manifests among them) type a struct
//! parameter as a `$ref` into the schema's own `$defs`, those refs are
//! resolved for typing too. Anything else is ignored rather than rejected —
//! this is a guard rail for models, not a conformance checker, and a false
//! rejection is worse than a missed catch.

use serde_json::{Map, Value};

/// Turn whatever accumulated in a `tool_use` block's input into a JSON
/// object, and say what had to be done to get there.
///
/// The `Err` arm still yields a usable object (`{}`) — the caller journals
/// it so the record replays, and the accompanying message is what the model
/// is told when the call is dispatched.
pub fn repair_tool_input(raw: &str) -> Result<Value, (Value, String)> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Ok(Value::Object(Map::new()));
    }
    if let Ok(Value::Object(o)) = serde_json::from_str::<Value>(trimmed) {
        return Ok(Value::Object(o));
    }

    // The common gateway failure: several complete JSON values run together
    // (`{"path":"a"}{"path":"b"}`), because two tool calls were collapsed
    // onto one stream index. The first value is the one this block is for;
    // the rest belonged to a call that was already lost upstream.
    if let Some((first, rest)) = first_json_value(trimmed)
        && let Value::Object(o) = first
    {
        let rest = rest.trim();
        return if rest.is_empty() {
            Ok(Value::Object(o))
        } else {
            tracing::warn!(trailing = %truncate(rest, 200), "tool input had trailing data after the first JSON object; using the first");
            Ok(Value::Object(o))
        };
    }

    // A bare scalar, a fragment, or template noise. Nothing here is safe to
    // guess at, so journal an empty object and let the model be told why.
    Err((
        Value::Object(Map::new()),
        format!(
            "the arguments for this call were not a JSON object (got `{}`)",
            truncate(trimmed, 200)
        ),
    ))
}

/// Parse one complete JSON value off the front of `s`, returning it and the
/// unconsumed remainder. `serde_json`'s `StreamDeserializer` does the
/// bracket matching so string escapes and nesting are handled correctly.
fn first_json_value(s: &str) -> Option<(Value, &str)> {
    let mut de = serde_json::Deserializer::from_str(s).into_iter::<Value>();
    let v = de.next()?.ok()?;
    Some((v, &s[de.byte_offset()..]))
}

fn truncate(s: &str, n: usize) -> String {
    if s.chars().count() <= n {
        return s.to_string();
    }
    let cut: String = s.chars().take(n).collect();
    format!("{cut}…")
}

/// Resolve a `$ref` against the schema that declared it. One hop is all
/// tool schemas actually use (`#/$defs/Name`, schemars's spelling); an
/// unresolvable or chained ref falls back to the schema as written, which
/// carries no `type` — so nothing is coerced and nothing complained about,
/// the conservative outcome either way.
fn resolve_ref<'a>(schema: &'a Value, root: &'a Value) -> &'a Value {
    let Some(pointer) = schema.get("$ref").and_then(Value::as_str) else {
        return schema;
    };
    let Some(path) = pointer.strip_prefix("#/") else {
        return schema;
    };
    let mut cursor = root;
    for segment in path.split('/') {
        match cursor.get(segment) {
            Some(next) => cursor = next,
            None => return schema,
        }
    }
    cursor
}

fn wants_object(schema: &Value) -> bool {
    schema.get("type").and_then(Value::as_str) == Some("object")
        || schema.get("properties").is_some_and(Value::is_object)
}

/// Repair, against the manifest, the one shape a streaming model gets wrong
/// in a way a server cannot forgive: a parameter the schema types as an
/// object — declared directly, or through a `$ref` into the schema's own
/// `$defs` — arriving as that object's JSON text. Where the string parses to
/// an object it is swapped in, recursively; everywhere else the input is
/// untouched. A string-typed parameter carrying JSON as *data* is never
/// rewritten: the schema, not the shape of the text, decides.
///
/// The 2026-09-06 night, for the record: glm-5.3 emitted a `$ref`-typed
/// parameter as its JSON string seven times running, the server's serde
/// rejected it seven times, and the model re-emitted the identical string
/// every retry — a rejection it could not act on, for a conversion that
/// costs nothing. Exactly the stringly-number mercy, one type over.
pub fn coerce(schema: &Value, input: &mut Value) {
    coerce_walk(schema, input, schema, "");
}

fn coerce_walk(schema: &Value, value: &mut Value, root: &Value, path: &str) {
    let schema = resolve_ref(schema, root);
    if wants_object(schema)
        && let Value::String(text) = &*value
        && let Ok(Value::Object(parsed)) = serde_json::from_str::<Value>(text)
    {
        tracing::debug!(field = %field(path), "repaired a string-encoded object parameter");
        *value = Value::Object(parsed);
    }
    if let Some(obj) = value.as_object_mut()
        && let Some(props) = schema.get("properties").and_then(Value::as_object)
    {
        for (name, child) in obj.iter_mut() {
            if let Some(child_schema) = props.get(name) {
                coerce_walk(child_schema, child, root, &join(path, name));
            }
        }
    }
    if let Some(arr) = value.as_array_mut()
        && let Some(items) = schema.get("items")
    {
        for (i, child) in arr.iter_mut().enumerate() {
            coerce_walk(items, child, root, &format!("{path}[{i}]"));
        }
    }
}

/// Check `input` against a manifest's `input_schema`. `Err` is a message
/// written to be read by the model that made the call.
pub fn validate(tool: &str, schema: &Value, input: &Value) -> Result<(), String> {
    let mut problems = Vec::new();
    check(schema, input, "", &mut problems, schema);
    if problems.is_empty() {
        return Ok(());
    }
    let mut msg = format!(
        "`{tool}` was called with invalid arguments: {}",
        problems.join("; ")
    );
    if let Some(example) = example_call(schema) {
        msg.push_str(&format!(". Expected shape: {example}"));
    }
    Err(msg)
}

fn check(schema: &Value, value: &Value, path: &str, out: &mut Vec<String>, root: &Value) {
    let schema = resolve_ref(schema, root);
    let Some(schema) = schema.as_object() else {
        return;
    };

    if let Some(expected) = schema.get("type").and_then(Value::as_str)
        && !type_matches(expected, value)
    {
        out.push(format!(
            "{} must be {}, got {}",
            field(path),
            article(expected),
            describe(value)
        ));
        // A wrong type makes every nested complaint noise.
        return;
    }

    if let Some(vals) = schema.get("enum").and_then(Value::as_array)
        && !vals.contains(value)
    {
        let allowed: Vec<String> = vals.iter().map(render).collect();
        out.push(format!(
            "{} must be one of {}, got {}",
            field(path),
            allowed.join(", "),
            render(value)
        ));
    }

    if let Some(obj) = value.as_object() {
        let props = schema.get("properties").and_then(Value::as_object);
        for name in schema
            .get("required")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            let Some(name) = name.as_str() else { continue };
            if !obj.contains_key(name) {
                let ty = props
                    .and_then(|p| p.get(name))
                    .map(|s| resolve_ref(s, root))
                    .and_then(|s| s.get("type"))
                    .and_then(Value::as_str)
                    .map(|t| format!(" ({t})"))
                    .unwrap_or_default();
                out.push(format!("missing required field `{}`{ty}", join(path, name)));
            }
        }
        if let Some(props) = props {
            for (k, v) in obj {
                if let Some(s) = props.get(k) {
                    check(s, v, &join(path, k), out, root);
                }
            }
        }
    }

    if let Some(arr) = value.as_array()
        && let Some(items) = schema.get("items")
    {
        for (i, v) in arr.iter().enumerate() {
            check(items, v, &format!("{path}[{i}]"), out, root);
        }
    }
}

fn type_matches(expected: &str, v: &Value) -> bool {
    match expected {
        "object" => v.is_object(),
        "array" => v.is_array(),
        "string" => v.is_string(),
        // Models routinely send numbers as strings and integers as floats.
        // Accepting what converts losslessly is kinder than a rejection the
        // model has to guess its way out of.
        "integer" => {
            v.as_i64().is_some()
                || v.as_f64().is_some_and(|f| f.fract() == 0.0)
                || v.as_str().is_some_and(|s| s.trim().parse::<i64>().is_ok())
        }
        "number" => v.is_number() || v.as_str().is_some_and(|s| s.trim().parse::<f64>().is_ok()),
        "boolean" => {
            v.is_boolean()
                || v.as_str()
                    .is_some_and(|s| matches!(s.trim(), "true" | "false"))
        }
        "null" => v.is_null(),
        _ => true,
    }
}

fn describe(v: &Value) -> &'static str {
    match v {
        Value::Null => "null",
        Value::Bool(_) => "a boolean",
        Value::Number(_) => "a number",
        Value::String(_) => "a string",
        Value::Array(_) => "an array",
        Value::Object(_) => "an object",
    }
}

fn article(t: &str) -> String {
    let a = if t.starts_with(['a', 'e', 'i', 'o', 'u']) {
        "an"
    } else {
        "a"
    };
    format!("{a} {t}")
}

fn render(v: &Value) -> String {
    match v {
        Value::String(s) => format!("`{s}`"),
        other => format!("`{other}`"),
    }
}

fn field(path: &str) -> String {
    if path.is_empty() {
        "the input".into()
    } else {
        format!("`{path}`")
    }
}

fn join(path: &str, name: &str) -> String {
    if path.is_empty() {
        name.to_string()
    } else {
        format!("{path}.{name}")
    }
}

/// A one-line example object built from the schema's required fields, shown
/// alongside a validation failure so the correction is mechanical.
pub fn example_call(schema: &Value) -> Option<String> {
    let props = schema.get("properties")?.as_object()?;
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    // With nothing marked required, showing every property is still a
    // better hint than showing none.
    let keys: Vec<&str> = if required.is_empty() {
        props.keys().map(String::as_str).collect()
    } else {
        required
    };
    if keys.is_empty() {
        return None;
    }
    let mut o = Map::new();
    for k in keys {
        let ty = props
            .get(k)
            .map(|s| resolve_ref(s, schema))
            .and_then(|s| s.get("type"))
            .and_then(Value::as_str)
            .unwrap_or("string");
        o.insert(k.to_string(), placeholder(ty, k));
    }
    Some(Value::Object(o).to_string())
}

fn placeholder(ty: &str, name: &str) -> Value {
    match ty {
        "integer" | "number" => Value::from(1),
        "boolean" => Value::Bool(true),
        "array" => Value::Array(vec![]),
        "object" => Value::Object(Map::new()),
        _ => Value::String(format!("<{name}>")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn write_schema() -> Value {
        json!({
            "type": "object",
            "properties": {
                "path": { "type": "string" },
                "content": { "type": "string" },
            },
            "required": ["path", "content"],
        })
    }

    #[test]
    fn concatenated_objects_keep_the_first() {
        // The exact blob litellm produced when ministral emitted two tool
        // calls that the gateway collapsed onto one stream index.
        let raw = r#"{"path": "hello.txt", "content": "hello"}{"path": "hello.txt"}"#;
        let v = repair_tool_input(raw).expect("repairable");
        assert_eq!(v, json!({ "path": "hello.txt", "content": "hello" }));
        // And what we keep is round-trippable, which is the whole point.
        serde_json::from_str::<Value>(&v.to_string()).unwrap();
    }

    #[test]
    fn empty_and_whitespace_become_an_object() {
        assert_eq!(repair_tool_input("").unwrap(), json!({}));
        assert_eq!(repair_tool_input("  \n ").unwrap(), json!({}));
    }

    #[test]
    fn trailing_template_noise_is_dropped() {
        let raw = r#"{"path": "a.txt"} write[ARGS]{"path":"#;
        assert_eq!(repair_tool_input(raw).unwrap(), json!({ "path": "a.txt" }));
    }

    #[test]
    fn a_non_object_still_yields_a_replayable_record() {
        let (v, why) = repair_tool_input("just some prose").unwrap_err();
        assert_eq!(v, json!({}));
        assert!(why.contains("not a JSON object"), "{why}");
        serde_json::from_str::<Value>(&v.to_string()).unwrap();
    }

    #[test]
    fn a_json_array_is_not_an_object() {
        let (v, _) = repair_tool_input(r#"["a","b"]"#).unwrap_err();
        assert_eq!(v, json!({}));
    }

    #[test]
    fn missing_required_fields_are_named_with_an_example() {
        let err = validate("write", &write_schema(), &json!({})).unwrap_err();
        assert!(
            err.contains("missing required field `path` (string)"),
            "{err}"
        );
        assert!(
            err.contains("missing required field `content` (string)"),
            "{err}"
        );
        assert!(err.contains(r#""path":"<path>""#), "{err}");
    }

    #[test]
    fn a_non_object_input_is_reported_as_such() {
        let err = validate("write", &write_schema(), &json!("hello.txt")).unwrap_err();
        assert!(
            err.contains("the input must be an object, got a string"),
            "{err}"
        );
    }

    #[test]
    fn wrong_property_types_are_named() {
        let err = validate(
            "write",
            &write_schema(),
            &json!({ "path": 3, "content": "x" }),
        )
        .unwrap_err();
        assert!(
            err.contains("`path` must be a string, got a number"),
            "{err}"
        );
    }

    #[test]
    fn stringly_typed_numbers_and_bools_are_accepted() {
        let schema = json!({
            "type": "object",
            "properties": { "offset": { "type": "integer" }, "all": { "type": "boolean" } },
        });
        // Small models send "10" and "true" constantly; rejecting these
        // teaches them nothing and costs a round trip.
        validate("read", &schema, &json!({ "offset": "10", "all": "true" })).unwrap();
        validate("read", &schema, &json!({ "offset": 10.0 })).unwrap();
        assert!(validate("read", &schema, &json!({ "offset": "ten" })).is_err());
    }

    #[test]
    fn a_valid_call_passes() {
        validate(
            "write",
            &write_schema(),
            &json!({ "path": "a", "content": "b" }),
        )
        .unwrap();
    }

    #[test]
    fn enums_list_what_was_allowed() {
        let schema =
            json!({ "type": "object", "properties": { "mode": { "enum": ["fast", "slow"] } } });
        let err = validate("t", &schema, &json!({ "mode": "medium" })).unwrap_err();
        assert!(err.contains("must be one of `fast`, `slow`"), "{err}");
    }

    #[test]
    fn unconstrained_schemas_accept_anything() {
        validate("t", &json!({ "type": "object" }), &json!({ "whatever": 1 })).unwrap();
    }

    /// The schemars shape: a struct parameter typed as `$ref` into `$defs`.
    fn ref_schema() -> Value {
        json!({
            "type": "object",
            "properties": {
                "call": { "$ref": "#/$defs/LibRpcCall" },
            },
            "required": ["call"],
            "$defs": {
                "LibRpcCall": {
                    "type": "object",
                    "properties": { "function": { "type": "string" } },
                    "required": ["function"],
                },
            },
        })
    }

    /// The 2026-09-06 shape exactly: glm streamed an object-typed parameter
    /// as its JSON text, seven times, and the server's serde rejected all
    /// seven. Coercion swaps the object in, and validation then passes.
    #[test]
    fn string_encoded_objects_are_repaired_where_the_schema_wants_an_object() {
        let schema = ref_schema();
        let mut input = json!({ "call": "{\"function\": \"list\"}" });
        coerce(&schema, &mut input);
        assert_eq!(input["call"], json!({ "function": "list" }));
        validate("lib_rpc", &schema, &input).unwrap();
    }

    /// A plain `type: object` parameter gets the same repair — the `$ref`
    /// was never the point, the declared type was.
    #[test]
    fn plain_object_parameters_are_repaired_too() {
        let schema = json!({
            "type": "object",
            "properties": { "bindings": { "type": "object" } },
        });
        let mut input = json!({ "bindings": "{\"a\": \"merge pr 41\"}" });
        coerce(&schema, &mut input);
        assert_eq!(input["bindings"], json!({ "a": "merge pr 41" }));
    }

    /// The schema, not the shape of the text, decides: a string-typed
    /// parameter carrying JSON as data is never rewritten.
    #[test]
    fn string_typed_parameters_are_never_rewritten() {
        let schema = json!({
            "type": "object",
            "properties": { "script": { "type": "string" } },
        });
        let mut input = json!({ "script": "{\"main\": \"not an object param\"}" });
        coerce(&schema, &mut input);
        assert_eq!(
            input["script"],
            json!("{\"main\": \"not an object param\"}")
        );
    }

    /// A string that doesn't parse to an object is left in place so
    /// validation can name it in prose the model can act on.
    #[test]
    fn unparseable_strings_are_left_for_validation_to_name() {
        let schema = ref_schema();
        let mut input = json!({ "call": "list" });
        coerce(&schema, &mut input);
        assert_eq!(input["call"], json!("list"));
        let err = validate("lib_rpc", &schema, &input).unwrap_err();
        assert!(
            err.contains("`call` must be an object, got a string"),
            "{err}"
        );
    }

    /// With refs resolved, a wrong type at a `$ref`-typed parameter is
    /// named at home instead of sailing through to a server's serde.
    #[test]
    fn ref_typed_parameters_are_type_checked_after_resolution() {
        let err = validate("lib_rpc", &ref_schema(), &json!({ "call": 3 })).unwrap_err();
        assert!(
            err.contains("`call` must be an object, got a number"),
            "{err}"
        );
    }

    #[test]
    fn ref_typed_parameters_get_object_examples() {
        let err = validate("lib_rpc", &ref_schema(), &json!({ "call": "list" })).unwrap_err();
        assert!(err.contains(r#"Expected shape: {"call":{}}"#), "{err}");
    }

    /// Repair reaches through arrays: an item schema that says object
    /// repairs a string-encoded item.
    #[test]
    fn repair_reaches_array_items() {
        let schema = json!({
            "type": "object",
            "properties": {
                "steps": { "type": "array", "items": { "type": "object" } },
            },
        });
        let mut input = json!({ "steps": ["{\"n\": 1}", "kept"] });
        coerce(&schema, &mut input);
        assert_eq!(input["steps"][0], json!({ "n": 1 }));
        // A string that isn't an object stays a string; the schema's items
        // said object, so validation will say so — coercion doesn't guess.
        assert_eq!(input["steps"][1], json!("kept"));
    }
}
