//! What the binary ships, unpacked beside what the operator wrote.
//!
//! Every script the harness runs by default — the built-in tools, the
//! policy table, the UI layout and its prelude, the shipped providers —
//! is embedded in the binary, and used to stay there: an operator who
//! wanted to see how `read` was written, or to start a `ui.rn` from the
//! default, read the source tree or nothing, and an agent asked to write a
//! tool had no worked example on the machine at all. So on launch the
//! shipped set is unpacked to `~/.config/eidolon/system/` — the reference,
//! kept in lockstep with the binary — and the scripts the operator is
//! meant to edit are *seeded* one level up, where the loaders read them.
//! The arrangement is Melete's (`system_assets.rs`): a stamped reference
//! tree, and a live tier seeded when absent and reconciled on an upgrade.
//!
//! ## Two tiers
//!
//! `system/` is wiped and rewritten whenever [`stamp_of`] — a CRC over every
//! shipped file — differs from `system/.stamp`, so it is the running
//! binary's copy exactly and never anything else. Nothing reads it; it is
//! there to be read. `RUNE.md` in it is the guide for whoever writes the
//! next script, and `README.md` says this contract.
//!
//! The live tier is what the loaders read: `tools/<name>.rn` for every
//! built-in tool (`eidolon_rune::register_builtins` takes the file over
//! the binary), `policy.rn` (`ScriptPolicy::load` already did) and
//! `ui.rn` (the TUI already did). It is seeded when absent, on every
//! launch, so the set on disk is complete, and **never overwritten on the
//! strength of existing**. On an upgrade it is reconciled: a live file
//! still byte-identical to what the *previous* binary shipped was never
//! edited, so it is carried forward to what this one ships; anything else
//! is the operator's and is left exactly as it is, said once on stderr,
//! with the new version in `system/` to diff against. The previous
//! binary's copy is read off `system/` immediately before the wipe, which
//! is why no manifest is kept. A box whose `system/` predates the
//! mechanism has no baseline, and an absent baseline proves nothing — so
//! a differing file is kept, the right posture for an edit this code
//! cannot see. Nothing of the operator's is ever deleted, and a file this
//! release drops stays where it is (as a tool of its own, from then on).
//!
//! ## What is not seeded, and why
//!
//! Providers. A script in `providers_dir` loads *after* the `[[providers]]`
//! patches in `config.toml` and replaces the built-in whole, so a seeded
//! `openrouter.rn` would discard the patch that names the key — and on this
//! machine that directory is generated by Nix in any case, a symlink into
//! the store. `system/providers/` is the reference; the patch table is the
//! way to change a field of a built-in and a script of one's own the way
//! to change its wire. `prelude.rn` is compiled in front of every `ui.rn`
//! and never read from disk; it is unpacked so the builders `ui.rn` calls
//! can be read. The examples are starting points and not behaviour.
//!
//! ## The cost
//!
//! Steady state is one small read and a CRC over about a hundred
//! kilobytes — tens of microseconds against the startup budget — done
//! before the loaders so the launch that upgrades reads what it seeded.
//! Nothing here fails a launch: every problem is a line on stderr, and
//! the loaders fall back to the binary when a file is missing.

use std::collections::BTreeMap;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result};

/// The directory under the config dir holding the shipped copies.
pub const SYSTEM_DIR: &str = "system";
/// The version file inside it.
const STAMP: &str = ".stamp";

const README: &str = include_str!("../system/README.md");
const RUNE_GUIDE: &str = include_str!("../system/RUNE.md");
const GATEWAY_EXAMPLE: &str = include_str!("../../../examples/providers/gateway.rn");

/// One file the binary ships: where it lands under `system/`, and its text.
struct Shipped {
    rel: String,
    src: &'static str,
}

/// Everything the binary ships, in a fixed order (the stamp depends on it).
fn shipped() -> Vec<Shipped> {
    let mut out = Vec::new();
    for list in [
        eidolon_rune::BUILTINS,
        eidolon_rune::MNEME_BUILTINS,
        eidolon_rune::SWARM_BUILTINS,
        eidolon_rune::SEARCH_BUILTINS,
    ] {
        for (name, src) in list {
            out.push(Shipped {
                rel: format!("tools/{name}.rn"),
                src,
            });
        }
    }
    out.push(Shipped {
        rel: "policy.rn".into(),
        src: eidolon_rune::policy::DEFAULT_POLICY,
    });
    out.push(Shipped {
        rel: "ui.rn".into(),
        src: eidolon_tui::DEFAULT_UI,
    });
    out.push(Shipped {
        rel: "prelude.rn".into(),
        src: eidolon_tui::PRELUDE,
    });
    for (name, src) in eidolon_providers::catalog::BUILTINS {
        out.push(Shipped {
            rel: format!("providers/{name}.rn"),
            src,
        });
    }
    out.push(Shipped {
        rel: "examples/providers/gateway.rn".into(),
        src: GATEWAY_EXAMPLE,
    });
    out.push(Shipped {
        rel: "RUNE.md".into(),
        src: RUNE_GUIDE,
    });
    out.push(Shipped {
        rel: "README.md".into(),
        src: README,
    });
    out
}

/// Where a shipped file's *live* copy is — the one the loaders read — or
/// `None` for a file that is reference only. The tools directory is the
/// configured one, since that is where `register_builtins` looks.
fn live_path(rel: &str, config_dir: &Path, tools_dir: &Path) -> Option<PathBuf> {
    if let Some(name) = rel.strip_prefix("tools/") {
        return Some(tools_dir.join(name));
    }
    matches!(rel, "policy.rn" | "ui.rn").then(|| config_dir.join(rel))
}

/// The version stamp: a CRC over every shipped path and its text, with the
/// total length beside it. Stable for a binary, different for any binary
/// whose embedded scripts differ, and cheap enough to compute on the way
/// to the first frame.
fn stamp_of(files: &[Shipped]) -> String {
    let mut h = crc32fast::Hasher::new();
    let mut len = 0usize;
    for f in files {
        h.update(f.rel.as_bytes());
        h.update(b"\0");
        h.update(f.src.as_bytes());
        h.update(b"\0");
        len += f.src.len();
    }
    format!("{:08x}-{len}", h.finalize())
}

/// Bring the config directory up to what this binary ships: the reference
/// tree current, the live tier seeded and — on a version change —
/// reconciled. Returns what is worth saying, one line each; never fails.
pub fn sync(config_dir: &Path, tools_dir: &Path) -> Vec<String> {
    let files = shipped();
    let want = stamp_of(&files);
    let sys = config_dir.join(SYSTEM_DIR);
    let mut notes = Vec::new();
    let mut outcome = Outcome::default();
    let current = std::fs::read_to_string(sys.join(STAMP)).ok();
    if current.as_deref() != Some(want.as_str()) {
        // What the previous binary shipped, read before the wipe: the last
        // moment it exists, and the baseline the reconcile decides by.
        let baseline = read_tree(&sys);
        match unpack(config_dir, &sys, &files, &want) {
            Ok(()) => reconcile(
                config_dir,
                tools_dir,
                &files,
                &baseline,
                &mut outcome,
                &mut notes,
            ),
            Err(e) => notes.push(format!(
                "could not unpack the shipped scripts to {}: {e:#}",
                sys.display()
            )),
        }
    }
    seed(config_dir, tools_dir, &files, &mut outcome, &mut notes);
    outcome.say(config_dir, &mut notes);
    notes
}

/// Write the whole shipped set under `sys`, replacing what was there.
/// Built beside it and renamed into place, with the stamp written last,
/// so a tree that is only half there never carries a current stamp.
fn unpack(config_dir: &Path, sys: &Path, files: &[Shipped], stamp: &str) -> Result<()> {
    let tmp = config_dir.join(format!("{SYSTEM_DIR}.new.{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    let build = || -> Result<()> {
        for f in files {
            write_file(&tmp.join(&f.rel), f.src.as_bytes())?;
        }
        write_file(&tmp.join(STAMP), stamp.as_bytes())?;
        if sys.exists() {
            std::fs::remove_dir_all(sys).with_context(|| format!("clearing {}", sys.display()))?;
        }
        std::fs::rename(&tmp, sys).with_context(|| format!("moving {} into place", tmp.display()))
    };
    let out = build();
    if out.is_err() {
        let _ = std::fs::remove_dir_all(&tmp);
    }
    out
}

/// Every file under `root`, keyed by its path relative to `root` with `/`
/// separators. Best effort: a tree that is not there, or a file that will
/// not read, is simply absent — and an absent baseline entry only ever
/// means "cannot prove it untouched", which is the safe answer.
fn read_tree(root: &Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(root, &path, out);
            } else if let Ok(rel) = path.strip_prefix(root)
                && let Some(rel) = rel.to_str()
                && let Ok(bytes) = std::fs::read(&path)
            {
                out.insert(rel.replace('\\', "/"), bytes);
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

/// What happened to one live file.
#[derive(Debug, PartialEq, Eq)]
enum Refresh {
    /// Already what this binary ships.
    UpToDate,
    /// Was not there; written.
    Created,
    /// Untouched since the previous release; carried forward.
    Refreshed,
    /// Differs from both releases: the operator's, left alone.
    Kept,
}

/// Decide and apply the refresh for one live file. `previous` is what the
/// last binary shipped at this path — `None` when unknown, which never
/// justifies a write over something that exists.
fn refresh_file(path: &Path, previous: Option<&[u8]>, shipped: &[u8]) -> Result<Refresh> {
    let current = match std::fs::read(path) {
        Ok(bytes) => Some(bytes),
        Err(e) if e.kind() == ErrorKind::NotFound => None,
        Err(e) => return Err(e).with_context(|| format!("reading {}", path.display())),
    };
    let outcome = match current.as_deref() {
        None => Refresh::Created,
        Some(cur) if cur == shipped => return Ok(Refresh::UpToDate),
        // The decisive comparison: unchanged since the last release means a
        // stale seed, not an edit.
        Some(cur) if previous.is_some_and(|prev| prev == cur) => Refresh::Refreshed,
        Some(_) => return Ok(Refresh::Kept),
    };
    write_file(path, shipped)?;
    Ok(outcome)
}

/// After a version change: every live file, decided against the baseline.
fn reconcile(
    config_dir: &Path,
    tools_dir: &Path,
    files: &[Shipped],
    baseline: &BTreeMap<String, Vec<u8>>,
    outcome: &mut Outcome,
    notes: &mut Vec<String>,
) {
    for f in files {
        let Some(live) = live_path(&f.rel, config_dir, tools_dir) else {
            continue;
        };
        let shown = show(&live, config_dir);
        match refresh_file(
            &live,
            baseline.get(&f.rel).map(Vec::as_slice),
            f.src.as_bytes(),
        ) {
            Ok(Refresh::Created) => outcome.seeded.push(shown),
            Ok(Refresh::Refreshed) => outcome.refreshed.push(shown),
            Ok(Refresh::Kept) => outcome.kept.push(shown),
            Ok(Refresh::UpToDate) => {}
            Err(e) => notes.push(format!("{shown}: {e:#}")),
        }
    }
}

/// Every launch: a live file that is not there is written. One that is
/// there is not looked at — that is the reconcile's job, and only on an
/// upgrade, so an edited file is not reported on every start.
fn seed(
    config_dir: &Path,
    tools_dir: &Path,
    files: &[Shipped],
    outcome: &mut Outcome,
    notes: &mut Vec<String>,
) {
    for f in files {
        let Some(live) = live_path(&f.rel, config_dir, tools_dir) else {
            continue;
        };
        if live.exists() {
            continue;
        }
        let shown = show(&live, config_dir);
        match write_file(&live, f.src.as_bytes()) {
            Ok(()) => outcome.seeded.push(shown),
            Err(e) => notes.push(format!("{shown}: {e:#}")),
        }
    }
}

/// The three things a sync can have done, said as one line each.
#[derive(Default)]
struct Outcome {
    seeded: Vec<String>,
    refreshed: Vec<String>,
    kept: Vec<String>,
}

impl Outcome {
    fn say(self, config_dir: &Path, notes: &mut Vec<String>) {
        if !self.seeded.is_empty() {
            notes.push(format!(
                "seeded {} into {} (the shipped copies are in {SYSTEM_DIR}/, with RUNE.md beside them)",
                self.seeded.join(", "),
                config_dir.display()
            ));
        }
        if !self.refreshed.is_empty() {
            notes.push(format!(
                "refreshed to this release, untouched since the last: {}",
                self.refreshed.join(", ")
            ));
        }
        if !self.kept.is_empty() {
            notes.push(format!(
                "kept as you edited them; this release's copies are in {SYSTEM_DIR}/: {}",
                self.kept.join(", ")
            ));
        }
    }
}

/// A path as the operator would name it: relative to the config dir when
/// under it, whole otherwise (a `tools_dir` pointed elsewhere).
fn show(path: &Path, config_dir: &Path) -> String {
    path.strip_prefix(config_dir)
        .map(|r| r.display().to_string())
        .unwrap_or_else(|_| path.display().to_string())
}

fn write_file(path: &Path, bytes: &[u8]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(path, bytes).with_context(|| format!("writing {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read(p: &Path) -> String {
        std::fs::read_to_string(p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
    }

    fn stamp() -> String {
        stamp_of(&shipped())
    }

    fn builtin_tools() -> impl Iterator<Item = &'static (&'static str, &'static str)> {
        eidolon_rune::BUILTINS
            .iter()
            .chain(eidolon_rune::MNEME_BUILTINS)
            .chain(eidolon_rune::SWARM_BUILTINS)
            .chain(eidolon_rune::SEARCH_BUILTINS)
    }

    #[test]
    fn a_fresh_config_dir_gets_the_reference_tree_and_the_seeds() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path();
        let tools = cfg.join("tools");
        let notes = sync(cfg, &tools);
        assert_eq!(notes.len(), 1, "{notes:?}");
        assert!(
            notes[0].starts_with("seeded ")
                && notes[0].contains("tools/read.rn")
                && notes[0].contains("ui.rn"),
            "{notes:?}"
        );

        // The reference: everything, exactly as shipped, stamped.
        let sys = cfg.join(SYSTEM_DIR);
        assert_eq!(read(&sys.join(STAMP)), stamp());
        assert_eq!(
            read(&sys.join("tools/read.rn")),
            eidolon_rune::BUILTINS[0].1
        );
        assert_eq!(
            read(&sys.join("tools/peers.rn")),
            eidolon_rune::SWARM_BUILTINS[0].1
        );
        assert_eq!(
            read(&sys.join("policy.rn")),
            eidolon_rune::policy::DEFAULT_POLICY
        );
        assert_eq!(read(&sys.join("ui.rn")), eidolon_tui::DEFAULT_UI);
        assert_eq!(read(&sys.join("prelude.rn")), eidolon_tui::PRELUDE);
        assert_eq!(
            read(&sys.join("providers/zai.rn")),
            eidolon_providers::catalog::BUILTINS[1].1
        );
        assert!(read(&sys.join("examples/providers/gateway.rn")).contains("pub fn provider()"));
        assert!(read(&sys.join("RUNE.md")).contains("# Writing Rune for Eidolon"));
        assert!(read(&sys.join("README.md")).contains("binary-managed"));
        assert!(
            !cfg.join(format!("{SYSTEM_DIR}.new.{}", std::process::id()))
                .exists(),
            "the build dir was moved, not copied"
        );

        // The live tier: the tools, the table and the layout, and nothing
        // that is reference only.
        for (name, src) in builtin_tools() {
            assert_eq!(read(&tools.join(format!("{name}.rn"))), *src, "{name}");
        }
        assert_eq!(
            read(&cfg.join("policy.rn")),
            eidolon_rune::policy::DEFAULT_POLICY
        );
        assert_eq!(read(&cfg.join("ui.rn")), eidolon_tui::DEFAULT_UI);
        assert!(
            !cfg.join("providers").exists(),
            "providers are reference only"
        );
        assert!(!cfg.join("prelude.rn").exists() && !cfg.join("RUNE.md").exists());

        // A second launch on the same binary says nothing and rewrites
        // nothing: a marker dropped into the reference tree survives it.
        std::fs::write(sys.join("marker"), "still here").unwrap();
        assert!(sync(cfg, &tools).is_empty());
        assert!(sys.join("marker").exists());
    }

    #[test]
    fn an_upgrade_carries_the_untouched_forward_and_keeps_the_edited() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path();
        let tools = cfg.join("tools");
        sync(cfg, &tools);
        let sys = cfg.join(SYSTEM_DIR);
        // Pretend the previous binary shipped a different `read`, which
        // this box never touched; that the operator tuned `policy.rn`; and
        // that a tool shipped then has been dropped since.
        std::fs::write(sys.join(STAMP), "an-old-stamp").unwrap();
        std::fs::write(sys.join("tools/read.rn"), "// previous release").unwrap();
        std::fs::write(tools.join("read.rn"), "// previous release").unwrap();
        std::fs::write(sys.join("tools/gone.rn"), "// dropped since").unwrap();
        std::fs::write(cfg.join("policy.rn"), "// mine").unwrap();

        let notes = sync(cfg, &tools);
        assert_eq!(read(&sys.join(STAMP)), stamp());
        assert!(
            !sys.join("tools/gone.rn").exists(),
            "the reference is this binary's exactly"
        );
        assert_eq!(
            read(&tools.join("read.rn")),
            eidolon_rune::BUILTINS[0].1,
            "untouched: carried forward"
        );
        assert_eq!(
            read(&cfg.join("policy.rn")),
            "// mine",
            "edited: left alone"
        );
        assert_eq!(
            read(&cfg.join("ui.rn")),
            eidolon_tui::DEFAULT_UI,
            "already current: untouched"
        );
        assert_eq!(notes.len(), 2, "{notes:?}");
        assert!(
            notes.iter().any(|n| n.starts_with("refreshed")
                && n.contains("tools/read.rn")
                && !n.contains("ui.rn")),
            "{notes:?}"
        );
        assert!(
            notes
                .iter()
                .any(|n| n.starts_with("kept") && n.contains("policy.rn") && n.contains("system/")),
            "{notes:?}"
        );
    }

    /// A box that predates the mechanism has a `policy.rn` of its own and
    /// no `system/` to say what it started from. Nothing can be proved
    /// about it, so it is kept — and said, once, since this launch is the
    /// upgrade.
    #[test]
    fn without_a_baseline_a_differing_file_is_kept() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path();
        std::fs::write(
            cfg.join("policy.rn"),
            "// tuned before there was a system dir",
        )
        .unwrap();
        let notes = sync(cfg, &cfg.join("tools"));
        assert_eq!(
            read(&cfg.join("policy.rn")),
            "// tuned before there was a system dir"
        );
        assert!(
            notes
                .iter()
                .any(|n| n.starts_with("kept") && n.contains("policy.rn")),
            "{notes:?}"
        );
        assert!(
            notes
                .iter()
                .any(|n| n.starts_with("seeded") && n.contains("ui.rn")),
            "{notes:?}"
        );
    }

    /// Between upgrades the live tier is only ever *completed*: a seed the
    /// operator deleted comes back, and one they edited is not looked at.
    #[test]
    fn a_deleted_seed_comes_back_and_an_edited_one_is_not_mentioned() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path();
        let tools = cfg.join("tools");
        sync(cfg, &tools);
        std::fs::remove_file(tools.join("bash.rn")).unwrap();
        std::fs::write(cfg.join("ui.rn"), "// mine").unwrap();
        let notes = sync(cfg, &tools);
        assert_eq!(read(&tools.join("bash.rn")), eidolon_rune::BUILTINS[3].1);
        assert_eq!(read(&cfg.join("ui.rn")), "// mine");
        assert_eq!(notes.len(), 1, "{notes:?}");
        assert!(
            notes[0].starts_with("seeded tools/bash.rn into"),
            "{notes:?}"
        );
    }

    /// The tools go where the loader looks, which `tools_dir` may have
    /// moved; a path outside the config dir is named whole.
    #[test]
    fn the_tools_are_seeded_into_the_configured_directory() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("config");
        let elsewhere = dir.path().join("elsewhere");
        let notes = sync(&cfg, &elsewhere);
        assert!(elsewhere.join("read.rn").exists());
        assert!(!cfg.join("tools").exists());
        assert!(
            cfg.join(SYSTEM_DIR).join("tools/read.rn").exists(),
            "the reference tree is fixed"
        );
        assert!(
            notes[0].contains(&elsewhere.join("read.rn").display().to_string()),
            "{notes:?}"
        );
    }

    #[test]
    fn refresh_file_decides_by_the_previous_release() {
        let dir = tempfile::tempdir().unwrap();
        let f = dir.path().join("f");
        assert_eq!(
            refresh_file(&f, Some(b"old"), b"new").unwrap(),
            Refresh::Created
        );
        assert_eq!(std::fs::read(&f).unwrap(), b"new");
        assert_eq!(
            refresh_file(&f, Some(b"old"), b"new").unwrap(),
            Refresh::UpToDate
        );
        std::fs::write(&f, b"old").unwrap();
        assert_eq!(
            refresh_file(&f, Some(b"old"), b"new").unwrap(),
            Refresh::Refreshed
        );
        assert_eq!(std::fs::read(&f).unwrap(), b"new");
        std::fs::write(&f, b"MINE").unwrap();
        assert_eq!(
            refresh_file(&f, Some(b"old"), b"new").unwrap(),
            Refresh::Kept
        );
        assert_eq!(
            refresh_file(&f, None, b"new").unwrap(),
            Refresh::Kept,
            "no baseline proves nothing"
        );
        assert_eq!(std::fs::read(&f).unwrap(), b"MINE");
    }

    #[test]
    fn the_stamp_is_stable_and_names_its_size() {
        assert_eq!(stamp(), stamp());
        let s = stamp();
        let (crc, len) = s.split_once('-').unwrap();
        assert_eq!(crc.len(), 8);
        assert!(len.parse::<usize>().unwrap() > 10_000);
    }
}
