"""Generate loader.js: the runtime icon swapper for the Minerva skin.

Open WebUI's index.html loads /static/loader.js (deferred) and ships it empty
-- the JS twin of the custom.css hook. That is the only honest way to reach
every icon: the frontend is compiled Svelte, its icons are inline <svg> with
no stable hooks, and CSS cannot select by path data.

So: fingerprint each shipped icon by its normalised inner markup, and at
runtime replace the innards of any <svg> whose fingerprint we recognise. The
element, its classes, its size and its aria-label are left exactly as they
were -- only the picture changes.

Inputs:  owui-icons.json  (extracted from the bundle)
         icon-map-full.json  (id -> dinkie name, from the mapping workflow)
         dinkie-bodies.json  (name -> {body,width,height} from the Iconify API)
Output:  loader.js
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else HERE

icons = json.load(open(os.path.join(SRC, "owui-icons.json"), encoding="utf-8"))
mapping = json.load(open(os.path.join(SRC, "icon-map-full.json"), encoding="utf-8"))
bodies = json.load(open(os.path.join(SRC, "dinkie-bodies.json"), encoding="utf-8"))

NUM = re.compile(r"-?\d+(?:\.\d+)?")


def fit_viewbox(body, w, h):
    """dinkie's `-small` variants declare 8x8 but draw to y=9; widen to fit."""
    xs, ys = [], []
    for seg in re.findall(r"[MmLlHhVv][^A-Za-z]*", body):
        nums = [float(n) for n in NUM.findall(seg)]
        if seg[0] in "Hh":
            xs += nums
        elif seg[0] in "Vv":
            ys += nums
        else:
            xs += nums[0::2]
            ys += nums[1::2]
    if xs:
        w = max(w, max(xs))
    if ys:
        h = max(h, max(ys))
    return w, h


by_id = {r["id"]: r for r in icons}
table = {}
skipped = 0

for entry in mapping:
    i, name = entry["id"], entry["icon"]
    if not name or i not in by_id:
        skipped += 1
        continue
    b = bodies.get(name)
    if not b:
        skipped += 1
        continue
    w, h = fit_viewbox(b["body"], b.get("width", 12), b.get("height", 12))
    body = b["body"]
    # dinkie has no thumbs-DOWN -- only thumbs-up. Rather than leave the
    # dislike button as the one stray Heroicon in a row of pixel art, derive
    # it: a thumbs-down IS a thumbs-up turned through half a circle, which is
    # how most packs draw the pair anyway. Baked into the markup as a <g>
    # rather than a CSS transform so the app's own classes cannot fight it.
    if entry.get("transform") == "rotate180":
        body = f'<g transform="rotate(180 {w / 2:g} {h / 2:g})">{body}</g>'
    # key: the normalised inner markup of the shipped icon
    table[by_id[i]["inner"]] = {
        "vb": f"0 0 {w:g} {h:g}",
        "b": body,
    }

print(f"{len(table)} icons in the swap table ({skipped} left as shipped)")

js = """/* Minerva -- runtime icon swap and eidolon nav rows for Open WebUI.
 *
 * index.html loads this file (deferred) and ships it EMPTY: it is the
 * supported JS hook, the twin of /static/custom.css. Nothing here patches the
 * application bundle, so an `open-webui` upgrade cannot half-break it -- at
 * worst a fingerprint stops matching and that icon quietly stays as shipped.
 *
 * WHY a runtime swap rather than CSS: the frontend is compiled Svelte and its
 * icons are inline <svg> with no stable per-icon hook. CSS can mask a handful
 * of buttons that happen to carry ids; it cannot reach the rest, and it
 * cannot select by path data. Matching the markup can.
 *
 * HOW: every shipped icon is fingerprinted by its normalised inner markup.
 * When one is recognised, only its innards and viewBox are replaced -- the
 * <svg> element itself, its classes, sizing, and any aria-label stay exactly
 * as the app wrote them, so layout and accessibility are untouched.
 *
 * SECOND JOB, added for C5: three nav rows pointing at the pages eidolon
 * serves on its own port. See `addNav` at the bottom for why that is DOM
 * this file is allowed to add, and what it does when the nav moves.
 *
 * Icons: Dinkie Icons by atelierAnchor, MIT.
 *   https://github.com/atelier-anchor/dinkie-icons
 *
 * Generated by webui/build-loader.py -- edit that, not this.
 */
(function () {
  'use strict';

  /* fingerprint -> { vb: viewBox, b: replacement markup } */
  var TABLE = __TABLE__;

  var DONE = '__hootIcon';   // marker so an icon is never swapped twice

  function norm(s) { return s.replace(/\\s+/g, ' ').trim(); }

  function swap(svg) {
    if (svg[DONE]) return;
    var hit = TABLE[norm(svg.innerHTML)];
    svg[DONE] = true;             // set even on a miss: markup will not change
    if (!hit) return;
    svg.setAttribute('viewBox', hit.vb);
    // dinkie draws with fill; the shipped Heroicons are mostly stroked, and a
    // leftover stroke would smear the pixel grid.
    svg.setAttribute('fill', 'currentColor');
    svg.removeAttribute('stroke');
    svg.removeAttribute('stroke-width');
    svg.style.imageRendering = 'pixelated';
    svg.innerHTML = hit.b;
  }

  function sweep(root) {
    if (!root || !root.querySelectorAll) return;
    var list = root.querySelectorAll('svg');
    for (var i = 0; i < list.length; i++) swap(list[i]);
  }

  /* ---- the three pages eidolon serves, as nav rows -------------------- *
   *
   * Open WebUI 0.11.3's sidebar hrefs are hard-coded template literals in
   * the compiled bundle and no configuration key adds a sixth, so a
   * custom.css rule anchored on href="/ext" is correct and matches
   * nothing. Decisions.md, 2026-09-18, amended the "the skin never adds
   * DOM" rule for exactly this: loader.js MAY add DOM adjacent to a stable
   * anchor, and every such addition MUST degrade to absence. So:
   *
   *   - the anchor is the app's own Workspace row, falling back to Notes.
   *     Both were read off the rendered page, not guessed from the bundle.
   *     If an upgrade moves or renames them, `seed` is null, nothing is
   *     added, and nothing breaks.
   *   - the row is CLONED rather than built, because the app renders two
   *     different shapes for the same link -- a labelled row when the
   *     sidebar is open, an icon-only button when it is collapsed to the
   *     rail -- and a clone is whichever one is on screen, with the app's
   *     own classes, hover states and dark-mode colours already on it.
   *   - the glyph comes from custom.css, off the absolute href. The
   *     cloned <svg> is hidden there rather than emptied here, so there is
   *     one place that decides what these rows look like.
   *
   */
  var SHIM_ORIGIN = 'http://127.0.0.1:8085';  /* hoot-shim-origin */
  var NAV = [
    { path: 'graph', label: 'Graphs' }
  ];

  var NAVMARK = 'data-hoot-nav';

  /* The app wraps each open-sidebar row in a div carrying data-id; the
   * collapsed rail has no such wrapper and the anchor's parent is the
   * whole row. Clone whichever one this is. */
  function navRow(a) {
    return (a.closest && a.closest('[data-id]')) || a.parentElement;
  }

  /* Replace the row's visible label. The rail has no text node at all --
   * the aria-label is the name there -- so a miss is expected, not an
   * error. */
  function relabel(el, text) {
    var w = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, null, false);
    var n;
    while ((n = w.nextNode())) {
      if (n.nodeValue && n.nodeValue.trim()) { n.nodeValue = text; return; }
    }
  }

  function addNav() {
    if (!NAV.length) return;
    var seed = document.querySelector('a[href="/workspace"]') ||
               document.querySelector('a[href="/notes"]');
    if (!seed) return;                       // nav moved: degrade to absence
    var row = navRow(seed);
    if (!row || !row.parentElement) return;
    // Already there? Svelte re-renders the sidebar on every navigation and
    // takes our rows with it, so this is a presence test each pass, not a
    // once-ever flag.
    if (row.parentElement.querySelector('[' + NAVMARK + ']')) return;
    var after = row;
    for (var i = 0; i < NAV.length; i++) {
      var clone = row.cloneNode(true);
      var a = clone.tagName === 'A' ? clone : clone.querySelector('a');
      if (!a) return;                        // shape changed: add nothing
      clone.setAttribute(NAVMARK, NAV[i].path);
      if (clone.hasAttribute('data-id')) clone.setAttribute('data-id', 'hoot' + NAV[i].path);
      // The app's ids are the skin's other hook; a second #sidebar-notes-button
      // would make both of them wrong.
      a.removeAttribute('id');
      a.setAttribute('href', '/workspace#minerva-' + NAV[i].path);
      a.setAttribute('aria-label', NAV[i].label);
      a.removeAttribute('target');
      a.addEventListener('click', function (event) {
        event.preventDefault();
        var hash = '#minerva-graph';
        if (location.hash === hash) window.dispatchEvent(new CustomEvent('minerva-panel', {detail: {tab: hash.slice(9),full:true}}));
        else location.hash = hash;
      });
      relabel(a, NAV[i].label);
      after.parentElement.insertBefore(clone, after.nextSibling);
      after = clone;
    }
  }

  function addExtensionMenu() {
    var seed = document.querySelector('a[href="/calendar"]') ||
      document.querySelector('[data-hoot-nav="graph"] a') ||
      document.querySelector('#sidebar a[href="/workspace"]');
    if (!seed) return;
    var row = seed.parentElement;
    if (row.parentElement.querySelector('[data-minerva-extensions]')) return;
    var item = row.cloneNode(true), link = item.querySelector('a');
    item.setAttribute('data-minerva-extensions','');
    link.href = '/workspace/tools#minerva-extensions';
    link.setAttribute('aria-label','Extensions'); relabel(link,'Extensions');
    link.addEventListener('click', function(event) {
      event.preventDefault();
      document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true}));
      if(location.hash === '#minerva-extensions') window.dispatchEvent(new CustomEvent('minerva-panel',{detail:{tab:'extensions',full:true}}));
      else location.hash = 'minerva-extensions';
    });
    row.after(item);
  }

  /* The Authentication tab. 0.11.3 rendered `aria-controls="tab-admin-authentication"`;
   * 0.11.4 builds the admin tabs at runtime and no id survives that the skin can name, so
   * the tab is found by its visible label first and its id second. Nothing is added when
   * neither answers: a settings page with no Authentication tab has no place for this
   * panel, and absence is what this file does then. */
  function authenticationTab(tabs) {
    var candidates = tabs.querySelectorAll('[aria-controls], [role="tab"], button');
    for (var i = 0; i < candidates.length; i++) {
      var controls = (candidates[i].getAttribute('aria-controls') || '').toLowerCase();
      var label = (candidates[i].textContent || '').trim().toLowerCase();
      if (controls === 'tab-admin-authentication' || controls.indexOf('authentication') >= 0 ||
        label === 'authentication') return candidates[i];
    }
    return null;
  }

  /* Where the selected tab's own content lives, under whichever shape this release
   * renders. 0.11.3's `form > div.overflow-y-auto` is tried first, then the wider forms. */
  function settingsContent(tabs) {
    var scope = tabs.parentElement || tabs;
    var shapes = ['form > div.overflow-y-auto', 'form div.overflow-y-auto', 'div.overflow-y-auto', 'form'];
    for (var i = 0; i < shapes.length; i++) {
      var found = scope.querySelector(shapes[i]);
      if (found && found !== tabs) return found;
    }
    return null;
  }

  function addCredentials() {
    var tabs = document.getElementById('settings-tabs-container');
    if (!tabs) return;
    var active = authenticationTab(tabs);
    var existing = document.getElementById('minerva-credentials-panel');
    if (!active || active.getAttribute('aria-selected') !== 'true') { if (existing) existing.remove(); return; }
    if (existing) return;
    var content = settingsContent(tabs);
    if (!content) return;
    var panel = document.createElement('section');
    panel.id = 'minerva-credentials-panel';
    function element(tag, text, cls) {
      var node = document.createElement(tag);
      if (text) node.textContent = text;
      if (cls) node.className = cls;
      return node;
    }
    panel.className = 'flex flex-col gap-2';
    panel.append(element('h3', 'Authentication', 'text-sm font-medium'));
    panel.append(element('p', 'Model provider keys and logins. Saved keys are never displayed.', 'text-xs'));
    var status = element('p', 'Loading credentials…', 'text-xs'); status.setAttribute('role', 'status');
    var rows = element('div', null, 'flex flex-col gap-2'); panel.append(status, rows); content.append(panel);
    async function request(action, data) {
      var options = {headers: {Authorization: 'Bearer ' + (localStorage.getItem('token') || '')}, cache: 'no-store'};
      if (data) { options.method = 'POST'; options.body = new URLSearchParams(data); }
      var result = await fetch('/api/v1/minerva/credentials' + action, options);
      if (!result.ok) throw new Error(result.status === 400 ? 'Change refused. Check the credential name, value and type.' :
        result.status === 401 || result.status === 403 ? 'Administrator authentication required. Reopen WebUI settings after signing in.' : 'Credential service unavailable. Check that Eidolon is running.');
      return result.json();
    }
    function button(label, handler) {
      var node = element('button', label, 'px-3.5 py-1.5 text-xs font-medium rounded-lg bg-gray-850 dark:bg-gray-850');
      node.type = 'button';
      node.addEventListener('click', handler); return node;
    }
    async function change(action, name, input, controls) {
      if (action === 'delete' && !window.confirm('Delete ' + name + '? You will need the original key to restore it.')) return;
      controls.forEach(function (c) { c.disabled = true; });
      status.textContent = 'Saving…';
      try {
        await request('/' + action, input ? {name: name, value: input.value} : {name: name});
        if (input) input.value = '';
        await load(); status.textContent = 'Updated.';
      } catch (error) { status.textContent = error.message; }
      finally { if (input) input.value = ''; controls.forEach(function (c) { c.disabled = false; }); }
    }
    async function load() {
      try {
        var data = await request('');
        if (!panel.isConnected) return;
        rows.replaceChildren();
        (data.keys || []).forEach(function (key) {
          var row = element('div', null, 'flex flex-col gap-1');
          var label = element('label', key.name + (key.stored ? ' — saved' : ' — not set'), 'text-xs font-medium');
          row.append(label);
          var controls = [];
          if (key.kind !== 'issued') {
            var input = element('input', null, 'w-full text-sm bg-transparent outline-hidden');
            input.type = 'password'; input.autocomplete = 'off';
            input.spellcheck = false; input.setAttribute('autocapitalize', 'off');
            input.setAttribute('aria-label', key.name + ' key'); input.placeholder = key.stored ? 'Replacement key' : 'API key';
            label.append(input); controls.push(input);
            var save = button(key.stored ? 'Replace key' : 'Save key', function () {
              if (!input.value.trim()) { status.textContent = 'Enter a key first.'; return; }
              change('set', key.name, input, controls);
            });
            row.append(save); controls.push(save);
            input.addEventListener('keydown', function (event) {
              if (event.key === 'Enter') { event.preventDefault(); event.stopPropagation(); save.click(); }
            });
          } else row.append(element('p', 'Issued tokens must be re-issued to rotate them.'));
          if (key.stored) {
            var remove = button('Delete key', function () { change('delete', key.name, null, controls); });
            row.append(remove); controls.push(remove);
          }
          rows.append(row);
        });
        (data.logins || []).forEach(function (login) {
          var row = element('div', null, 'flex flex-col gap-1');
          row.append(element('h4', login.provider || login.name, 'text-xs font-medium'),
            element('p', login.state, 'text-xs'));
          if (login.command) row.append(element('code', login.command));
          var recheck = button('Recheck login', function () { change('recheck', login.name, null, [recheck]); });
          row.append(recheck); rows.append(row);
        });
        status.textContent = data.error ? 'Credential store unavailable.' : '';
      } catch (error) { status.textContent = error.message; }
    }
    load();
  }

  var ROUTER_ORIGIN = 'http://127.0.0.1:8080';  /* hoot-router-origin */
  function addServingStatus() {
    if (document.getElementById('hoot-serving-status')) return;
    var main = document.getElementById('chat-container');
    if (!main) return;
    var status = document.createElement('div');
    status.id = 'hoot-serving-status';
    status.setAttribute('role', 'status');
    status.title = 'Server reachability, checked every 15 seconds. Does not indicate model readiness.';
    status.textContent = 'hoot checking | llama.cpp ... | eidolon ...';
    main.prepend(status);
    refreshServingStatus();
  }
  async function refreshServingStatus() {
    var checks = await Promise.all([ROUTER_ORIGIN + '/health', SHIM_ORIGIN + '/ext'].map(async function (url) {
      try {
        await fetch(url, { mode: 'no-cors', cache: 'no-store', signal: AbortSignal.timeout(3000) });
        return true;
      } catch (_) { return false; }
    }));
    var status = document.getElementById('hoot-serving-status');
    if (status) {
      status.textContent = 'hoot ' + (checks.every(Boolean) ? 'serving' : 'unreachable') +
        ' | llama.cpp ' + (checks[0] ? 'reachable' : 'unreachable') +
        ' | eidolon ' + (checks[1] ? 'reachable' : 'unreachable');
      status.dataset.ready = String(checks.every(Boolean));
    }
  }

  function start() {
    sweep(document.body);
    addNav();
    addCredentials();
    addExtensionMenu();
    if (!document.getElementById('minerva-workspace-script')) {
      var workspaceScript = document.createElement('script');
      workspaceScript.id = 'minerva-workspace-script'; workspaceScript.type = 'module';
      workspaceScript.src = '/static/workspace.js'; document.head.append(workspaceScript);
    }
    addServingStatus();
    setInterval(refreshServingStatus, 15000);
    // Svelte renders most of this UI after first paint and re-renders on every
    // navigation, so a one-shot sweep would catch almost nothing. Observe
    // instead, and coalesce bursts into one pass with rAF.
    var queued = false;
    new MutationObserver(function (records) {
      if (queued) return;
      queued = true;
      requestAnimationFrame(function () {
        queued = false;
        for (var i = 0; i < records.length; i++) {
          var added = records[i].addedNodes;
          for (var j = 0; j < added.length; j++) {
            var n = added[j];
            if (n.nodeType !== 1) continue;
            if (n.tagName === 'svg') swap(n); else sweep(n);
          }
        }
        // Not inside the loop above: the sidebar's rows can be replaced by
        // a burst this observer coalesced away, and addNav's own presence
        // test is cheaper than deciding from the record list whether it
        // needs running.
        addNav();
        addCredentials();
    addExtensionMenu();
        addServingStatus();
      });
    }).observe(document.body, { childList: true, subtree: true });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
})();
"""

js = js.replace("__TABLE__", json.dumps(table, separators=(",", ":"), ensure_ascii=False))
out = os.path.join(HERE, "loader.js")
open(out, "w", encoding="utf-8", newline="\n").write(js)
print(f"wrote {out} ({os.path.getsize(out)} bytes)")

from pathlib import Path
source = Path(HERE).parent / "eidolon/crates/web/assets/js/jev.js"
editor = source.read_text(encoding="utf-8")
helpers = editor[editor.index("function walk("):editor.index("// --- drawing")]
(Path(HERE) / "graph-adapter.js").write_text(
    'export function graphToFlow(doc) {\nconst RESERVED = ["PICK", "EMPTY", "ERROR"];\n' + helpers +
    '\nreturn toFlow(new Map());\n}\n', encoding="utf-8")
